version: '2'
services:
    springangcouchoauthproj1-couchbase:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - TYPE=MASTER
            - BUCKET=SpringAngCouchOauthProj1
    springangcouchoauthproj1-couchbase-node:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        environment:
            - TYPE=WORKER
            - BUCKET=SpringAngCouchOauthProj1
            - COUCHBASE_MASTER=springangcouchoauthproj1-couchbase
            - AUTO_REBALANCE=false
